
#define RETRO_TAPPING

#define USB_SUSPEND_WAKEUP_DELAY 0
#define SERIAL_NUMBER "ZlBBr/QzB0xm"
#define LAYER_STATE_8BIT

#define RGB_MATRIX_STARTUP_SPD 60

#define TAPPING_TERM 180
#define PERMISSIVE_HOLD
#define HOLD_ON_OTHER_KEY_PRESS
#define IGNORE_MOD_TAP_INTERRUPT