name: Build ZSA Voyager Firmware

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout this repo
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip gcc-arm-none-eabi binutils-arm-none-eabi git

      - name: Install QMK CLI
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install --user pipx
          python3 -m pipx ensurepath
          pipx install qmk

      - name: Clean existing qmk_firmware (if any)
        run: rm -rf qmk_firmware

      - name: Clone QMK Firmware with zsa modules
        run: |
          export PATH="$HOME/.local/bin:$PATH"
          qmk clone qmk/qmk_firmware
          cd qmk_firmware
          qmk setup --yes

      - name: Copy keymap and user code
        run: |
          cp -r ./zsa_github_firmware_repo/zsa_voyager_simple-colemak-dhm-layout-for-be_source ./qmk_firmware/keyboards/zsa/voyager/keymaps/ZlBBr_QzB0xm
          mkdir -p ./qmk_firmware/users/custom
          if [ -d "./zsa_github_firmware_repo/custom" ]; then
            cp -r ./zsa_github_firmware_repo/custom/* ./qmk_firmware/users/custom/
          fi

      - name: Compile firmware
        run: |
          export PATH="$HOME/.local/bin:$PATH"
          cd qmk_firmware
          qmk compile -kb zsa/voyager -km ZlBBr_QzB0xm

      - name: Upload firmware
        uses: actions/upload-artifact@v4
        with:
          name: voyager-firmware
          path: qmk_firmware/*.bin

