name: Build ZSA Voyager Firmware

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repo
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip gcc-arm-none-eabi binutils-arm-none-eabi

      - name: Install QMK CLI
        run: |
          pip3 install --upgrade pip
          pipx install qmk

      - name: Clone QMK Firmware
        run: |
          export PATH="$HOME/.local/bin:$PATH"
          git clone https://github.com/qmk/qmk_firmware.git
          cd qmk_firmware
          git submodule update --init --recursive

      - name: Copy keymap and custom code
        run: |
          cp -r ./zsa_github_firmware_repo/zsa_voyager_simple-colemak-dhm-layout-for-be_source ./qmk_firmware/keyboards/zsa/voyager/keymaps/ZlBBr_QzB0xm
          mkdir -p ./qmk_firmware/users/custom
          if [ -d "./zsa_github_firmware_repo/custom" ]; then
            cp -r ./zsa_github_firmware_repo/custom/* ./qmk_firmware/users/custom/
          fi

      - name: Compile firmware
        run: |
          export PATH="$HOME/.local/bin:$PATH"
          cd qmk_firmware
          qmk compile -kb zsa/voyager -km ZlBBr_QzB0xm

      - name: Upload firmware
        uses: actions/upload-artifact@v4
        with:
          name: voyager-firmware
          path: qmk_firmware/*.bin

